# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deacfbe40210f1ea3063045fe3b4253d722eace3b547159e01dabebea6c1b16ed2a61bdd51d3bd0deef7cbb9fbaf0d92530c1798da032f448d3dcf800cf99904

test:
  secret_key_base: 410d4352bcae6a77c2e6bcf621939b3252441ead4d4858389c3de7d5bfa273e9f69df4655fa1208cc8123fb237bc8379e43d2782045108418f5e07e978e2fa45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
